import os

if __name__ == '__main__':
    plugin_name: str = "CMakeUnreal.Build"
    test_proj_name: str = "CMakeBuildTest"
    os.system(f"dotnet-combine single-file . \
                --overwrite true \
                --output {plugin_name}.cs \
                --exclude \"{test_proj_name}\"/;bin/;obj/;AutogeneratedDir/;AssemblyInfo.cs;\"Source\CMake\Main.cs\"")
